config/routes.rb
PaperclipDemo::Application.routes.draw do
  get 'users/create'

	resources :sessions, only: [:new, :create, :destroy]
	resources :users, only: [:create]

	resources :friends
	root :to => 'friends#index'

	get '/signup' => 'users#new'
    post '/users' => 'users#create'

    get '/login' => 'sessions#new'
  	post '/login' => 'sessions#create'
  	get '/logout' => 'sessions#destroy'
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
  
  validates :name, presence: true
  validates :medium, presence: true
  validates :description, presence: true
  validates :avatar,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
    attachment_size: { less_than: 5.megabytes }

  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }
  
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :friends

	validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)
    user_id = current_user.id
    @friend.update(user_id: user_id)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render action: 'show', status: :created, location: @friend }
      else
        format.html { render action: 'new' }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_params
      params.require(:friend).permit(:avatar, :name, :medium, :description, :lat, :lng, :user_id)
    end

    #This is where the logic will go to sign up new users
    def signup

    end

    #This is where the logic will go to login with existing
    def signin
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
	    user = User.find_by_email(params[:email])
	    # If the user exists AND the password entered is correct.
	    if user && user.authenticate(params[:password])
	      # Save the user id inside the browser cookie. This is how we keep the user 
	      # logged in when they navigate around our website.
	      session[:user_id] = user.id
	      redirect_to '/'
	    else
	    # If user's login doesn't work, send them back to the login form.
	      redirect_to '/'
	    end
  	end

	def destroy
    	session[:user_id] = nil
    	redirect_to '/login'
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'User was successfully created.'
    else
      redirect_to '/layouts/application'
    end
  end

 private

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_form.html.erb
<%= form_for(@friend, multipart: true) do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :medium %>
    <%= f.text_field :medium %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :avatar%>
  </div>
  <div class="field">
    <%= f.hidden_field :lat, :id => "lat_field"%>
    <%= f.hidden_field :lng, :id => "lon_field"%>
  </div>
  <div class="actions">
    <%= f.submit 'Upload Art' %>
    <%= link_to 'Cancel', friends_path, class: 'button' %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
d<div class="friend" id="<%= friend.id %>">
  <div class="front">
    <%= link_to friend, class: 'pic-link' do %>
      <%= image_tag friend.avatar.url(:square) %>
    <% end %>
  </div>

  <div class="back">
    <span class="friend-name">
    <%= friend.name %>
    <%= friend.medium %>
    <%= friend.description %>
    </span>
    <div class="actions">
      <%= link_to 'Show', friend %>
      <%= link_to 'Edit', edit_friend_path(friend) %>
      <%= link_to 'Delete', friend, confirm: 'Are you sure you want to lose a friend?', method: :delete, class: 'destroy' %>
    </div>
  </div>
</div>

app/views/friends/edit.html.erb
<h1>Change your friend*</h1>

<%= render 'form' %>

<aside>* Do not try in real life</aside>

app/views/friends/index.html.erb
<h2 align="center" >Popular in Your Area</h2>
<p id="upload-btn"><%= link_to 'Upload Art', new_friend_path, class: 'new-friend' %></p>

<section id="friends">
  <%= render @friends %>
</section>

app/views/friends/new.html.erb
<h1>Add Art Details</h1>

<%= render 'form' %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
<%= @friend.name %>
<br>
<%= @friend.medium %>
<br>
<%= @friend.description %>
</h2>
  <%= image_tag @friend.avatar.url(:medium) %>

<div class="show actions">
  <%= link_to 'Edit', edit_friend_path(@friend) %>
  <%= link_to 'Remove', @friend, data: { confirm: 'Are you sure you want to lose a friend?' }, method: :delete, class: 'destroy' %>
  <%= link_to 'Back to my Gallery', friends_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>ArtSource</title>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
  <%= stylesheet_link_tag 'application', :media => 'all' %>
  <%= csrf_meta_tags %>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<link href="https://fonts.googleapis.com/css?family=Bungee+Inline" rel="stylesheet">

</head>

<body>
  <header>
    <div class="header-wrap">
      <h1><%= link_to 'ArtSource', root_path %><button id='open-signup'>Sign Up</button>
  <button id="open-login">Login</button></h1>
    </div>

    <div id="signup-form">
    <%=form_for :user, url: '/users' do |f| %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
        <br>
      <div class="field">
        <%= f.label :password %>
        <%= f.text_field :password %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.text_field :password_confirmation %>
      </div>
      <div>
      <%= f.submit "Submit" %>
      </div>
      <%end%>
    </div>

    <div id="signin-form">
    <%= form_tag '/login' do %>
      Email: <%= text_field_tag :email %>
      <br>
      <br>
      Password: <%= password_field_tag :password %>
      <br>
      <br>
      <%= submit_tag "Submit" %>
    <% end %>
    </div>
</header>

  <div class="jumbotron">
    <div class="col-md-7">
      <h2>the hub of art that brings value to your business</h2>
    </div>
  </div>

  <div id="main-wrap">
    <%= yield %>
  </div>

  <div class="animateblock top">

   <div id="info-jumbo">
     <div class="animateblock left">
     LEFT
      <img src="" alt="white ipod dock">
    </div>
    
    <div class="animateblock right">
    RIGHT
      <img src="" alt="white iphone">
    </div>
   </div>

   

  <div id="map"></div>

  <script>

      function initMap() {

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: {lat: 37.784705599999995, lng: -122.39762309999998}
        });

        // Create an array of alphabetical characters used to label the markers.
        var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

        // Add some markers to the map.
        // Note: The code uses the JavaScript Array.prototype.map() method to
        // create an array of markers based on a given "locations" array.
        // The map() method here has nothing to do with the Google Maps API.
        var markers = locations.map(function(location, i) {
          return new google.maps.Marker({
            position: location,
            label: labels[i % labels.length]
          });
        });

        // Add a marker clusterer to manage the markers.
        var markerCluster = new MarkerClusterer(map, markers,
            {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});
      }
      var locations = []
      <%Friend.all.each do |image|%>
        locations.push({lat: <%=image.lat%>, lng: <%=image.lng%>})
      <%end%>
    </script>
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js">
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyANmKVc7-NfVMhyHtT9YYCz6EsVjYnPrnA&callback=initMap">
    </script>

  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>